Comprehensive Codebase Refactor: DTO Updates, Database Migration Enhancements, Middleware Improvements, and Model Adjustments
pithmdtifub/warung-informatika-be pull request #6
Opened 2024-11-17 11:25 UTC by atha3417

This pull request introduces several changes to the codebase, focusing on refactoring the data transfer objects (DTOs), updating the database migration functions, and modifying the authentication and authorization middleware. The most important changes include the creation of new DTOs, updates to database migration functions, and improvements in the middleware for better handling of JWT tokens.

### DTO Refactoring:
* [`dto/category_dto.go`](diffhunk://#diff-86501a80ae1f24a2f9e7fd52ca1a5857a27a8ef04af4bb2c82826f491c8e64e0R1-R11): Added `CategoryRequest` and `CategoryResponse` structs to handle category data.
* [`dto/menu_dto.go`](diffhunk://#diff-a8ac615d39022af077f419deec78a16ea98d9a905179e339ccd20606a1ab002aR1-R19): Added `MenuRequest` and `MenuResponse` structs to handle menu data.
* [`dto/user_dto.go`](diffhunk://#diff-584fdf096ada97f249218bc47c0f72679fde0671046a501b6ba929af567fee1bR1-R6): Added `UserRequest` struct to handle user data.

### Database Migration Updates:
* [`database/migration.go`](diffhunk://#diff-5692f665a628e9ac2654d8d371a1a09b1929d8830bc1b3d20a15ba08023ec4ddL8-R20): Split the `Migrate` function into `MigrateUp` and `MigrateDown` functions for better migration control.

### Middleware Improvements:
* [`middlewares/require_admin_middleware.go`](diffhunk://#diff-41cf1307a3c1710d4be326daa507d9e0bbdf696e685f81af196c006bf93dffeeL6-R20): Refactored to use claims from `c.Locals` instead of parsing the token manually.
* [`middlewares/require_auth_middleware.go`](diffhunk://#diff-2aba9a69ab7d1786ed3f24b1803cce4c71c80873ee06627a1e79f6681ba49f43L22-R25): Improved token parsing logic and added claims to `c.Locals`. [[1]](diffhunk://#diff-2aba9a69ab7d1786ed3f24b1803cce4c71c80873ee06627a1e79f6681ba49f43L22-R25) [[2]](diffhunk://#diff-2aba9a69ab7d1786ed3f24b1803cce4c71c80873ee06627a1e79f6681ba49f43R46-R48)

### Model Updates:
* [`models/category.go`](diffhunk://#diff-feefc5018db042024992c97f1b37278e6a62746f0825f4e10fefd78a9ab24678L4-R6): Removed JSON and form tags from the `Category` struct.
* [`models/menu.go`](diffhunk://#diff-6b9ee48fcd6016d9465a0721ea94dd3ce2183113fc4c4ec49f033f629e9da806L4-R10): Removed JSON and form tags from the `Menu` struct.
* [`models/user.go`](diffhunk://#diff-f9c27c5d201f4eb9a23b855d52131aab43a1842aeedcf9356797c4ae75c224dfR3-R27): Updated the `User` struct to use `uuid` for the primary key and added a `BeforeCreate` hook.

### General Codebase Updates:
* [`.env.example`](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cL6-R6): Changed the default `PORT` from `8000` to `3000`.
* [`api/index.go`](diffhunk://#diff-18ca9ac0c83e1edbd6e4f8881b0991a18cab9a62897b4214c3017f0085170763L4-R7): Reorganized imports and added comments for potential database seeding functions. [[1]](diffhunk://#diff-18ca9ac0c83e1edbd6e4f8881b0991a18cab9a62897b4214c3017f0085170763L4-R7) [[2]](diffhunk://#diff-18ca9ac0c83e1edbd6e4f8881b0991a18cab9a62897b4214c3017f0085170763L25-R27)
* [`go.mod`](diffhunk://#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L19-R19): Updated the `github.com/google/uuid` dependency to version `1.6.0`.

2024-11-17 11:44 UTC, ahargunyllib commented on .env.example
ini kenapa di ganti wkwkwkw, biasanya api 8000 atau ngga 8080 sih, 3000 buat fe. tapi gapapa

2024-11-17 11:45 UTC, ahargunyllib commented on controllers/auth_controller.go
> +	if err != nil {
ini kalo error dari db better 500 internal server error sih, tp gapapa

2024-11-18 02:48 UTC, ahargunyllib commented on dto/category_dto.go
ini better di pisah sih buat tiap usecase, cth: create sm edit

2024-11-18 02:48 UTC, ahargunyllib commented on models/menu.go
ini bukannya harus ada references nya ya? aman kah kek gini

2024-11-18 02:48 UTC, ahargunyllib commented on models/user.go
> +	if u.Username == "" || u.Password == "" {
harusnya ini ga perlu. keknya kalo insert empty string bakal dianggap null, jd buat aja username sm passwordnya not nullable

2024-11-18 05:23 UTC, atha3417 commented on .env.example
OH YA, itu lupa soalnya kemarin lagi ada app yg make port 8000, jdnya make 3000 dulu, aku balikin

2024-11-18 05:55 UTC, atha3417 commented on models/menu.go
![image](https://github.com/user-attachments/assets/4e32800f-c4e9-4a3d-98b0-f82f5c11e9f0)
aman karena udah ada nilai default

2024-11-18 06:04 UTC, ahargunyllib requested changes

2024-11-18 06:04 UTC, ahargunyllib commented on controllers/auth_controller.go
> +		return c.Status(fiber.StatusUnauthorized).JSON(fiber.Map{"message": "Failed to login", "error": err})
ini harusnya ada if error is gorm.ErrNotFound baru invalid credentials, sisanya baru gini

2024-11-18 06:04 UTC, ahargunyllib commented on controllers/menu_controller.go
> +	category, _ := repositories.GetCategory(int(menuReq.CategoryID))
ini kenapa di cast

2024-11-18 09:00 UTC, atha3417 commented on controllers/menu_controller.go
> +	category, _ := repositories.GetCategory(int(menuReq.CategoryID))
karena kalo ga nanti error, menuReq.CategoryId tipe nya uint soalnya

2024-11-18 09:31 UTC, atha3417 commented on controllers/menu_controller.go
> +	category, _ := repositories.GetCategory(int(menuReq.CategoryID))
soalnya menuReq.CategoryID tipenya uint

2024-11-18 11:02 UTC, atha3417 commented on .env.example
biar sama semua pake double quote, ga cuma jwt secret sih

2024-11-18 11:32 UTC, merged