Enhance Menu Endpoints with Pagination, Search, and Update/Delete Functionality
pithmdtifub/warung-informatika-be pull request #8
Opened 2024-11-22 07:31 UTC by Ablebil

2024-11-22 07:40 UTC, ahargunyllib requested changes

2024-11-22 07:40 UTC, ahargunyllib commented on controllers/menu_controller.go
> +type MenuParams struct {
masukin ke dto aja

2024-11-22 07:40 UTC, ahargunyllib commented on controllers/menu_controller.go
> +	category := c.QueryInt("category", 0)
ini ada query parser, query struct nya masukin dto

2024-11-22 07:40 UTC, ahargunyllib commented on controllers/menu_controller.go
> +	menus, err := repositories.GetMenus(search, category, page, limit)
jadi ini nge pass struct bukan gini

2024-11-22 07:40 UTC, ahargunyllib commented on controllers/menu_controller.go
> +	if len(menus) == 0 {
ga perlu kondisi ini

2024-11-22 07:40 UTC, ahargunyllib commented on controllers/menu_controller.go
> +    menu.ID = uint(params.ID)
struct paramnya ganti ke uint aja

2024-11-27 20:51 UTC, Ablebil commented on controllers/menu_controller.go
> +	if len(menus) == 0 {
ini ngga perlu if len(menus) == 0 mas?

2024-11-28 05:37 UTC, ahargunyllib approved these changes
lgtm!

2024-11-28 16:33 UTC, merged